version: '3.1'
services:
  mongo:
    image: mongo
    container_name: 'gin-mongo-api'
    environment:
      - MONGO_INITDB_DATABASE=gin_mongo
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongo-volume:/data/db
    ports:
      - '27017:27017'
